[mcp]
enabled = true

[[mcp.servers]]
name = "aspire"
url = "http://localhost:3007/sse"

[[mcp.servers]]
name = "tavily"
url = "http://mcp-tavily:3001/sse"

[[mcp.servers]]
name = "azure-devops"
url = "http://mcp-azure-devops:3002/sse"

[[mcp.servers]]
name = "postman"
url = "http://mcp-postman:3003/sse"

[[mcp.servers]]
name = "new-relic"
url = "http://mcp-newrelic:3004/sse"

[[mcp.servers]]
name = "github"
url = "http://mcp-github:3005/sse"

[[mcp.servers]]
name = "playwright"
url = "http://mcp-playwright:3006/sse"
