---
- name: restart dnsmasq
  become: true
  ansible.builtin.systemd_service:
    name: dnsmasq
    state: restarted

- name: reload systemd-resolved
  become: true
  ansible.builtin.command: systemctl restart systemd-resolved
