[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          tail
    Path          /var/lib/docker/containers/*/*.log
    Parser        docker
    Tag           docker.*
    Refresh_Interval 10
    Mem_Buf_Limit 50MB
    Skip_Long_Lines On

[FILTER]
    Name          parser
    Match         docker.*
    Key_Name      log
    Parser        docker
    Reserve_Data  On

[OUTPUT]
    Name                 opentelemetry
    Match                *
    Host                 signoz-otel-collector
    Port                 4318
    Logs_uri             /v1/logs
    Log_response_payload True
    tls                  Off
    tls.verify           Off
