[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info

[INPUT]
    Name          tail
    Path          /var/lib/docker/containers/*/*.log
    Parser        docker
    Tag           docker.*
    Refresh_Interval 10
    Mem_Buf_Limit 50MB
    Skip_Long_Lines On

[FILTER]
    Name          parser
    Match         docker.*
    Key_Name      log
    Parser        docker
    Reserve_Data  On

[OUTPUT]
    Name          loki
    Match         *
    Host          observability-signoz
    Port          3100
    Labels        job=docker
    Auto_Kubernetes_Labels off
    Line_Format   json
