---
# VS Code CLI installation

- name: Check if VS Code CLI is already installed
  ansible.builtin.stat:
    path: "{{ admin_install_prefix }}/code"
  register: vscode_cli_stat

- name: Install VS Code CLI
  ansible.builtin.shell: |
    curl -fsSL "https://update.code.visualstudio.com/latest/cli-linux-x64/stable" | tar xz -C "{{ admin_install_prefix }}"
  args:
    creates: "{{ admin_install_prefix }}/code"
  become_user: root
  changed_when: false
