---
# C++ build tools installation

- meta: end_play
  when: not (cpp_enabled | bool)

- name: Install C++ build tools
  become: true
  ansible.builtin.apt:
    name:
      - clang
      - cmake
      - build-essential
    state: present
    update_cache: yes
