{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.createClusterSecretStore }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStoreName }}
  labels:
    {{- include "zzaia-workspace.labels" . | nindent 4 }}
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          secretAccessKey:
            name: {{ .Values.externalSecrets.bitwardensecretsmanager.accessTokenSecretName }}
            namespace: {{ .Values.externalSecrets.bitwardensecretsmanager.accessTokenSecretNamespace }}
            key: credentials
      organizationId: {{ .Values.externalSecrets.bitwardensecretsmanager.organizationId | quote }}
      {{- if .Values.externalSecrets.bitwardensecretsmanager.apiURL }}
      apiURL: {{ .Values.externalSecrets.bitwardensecretsmanager.apiURL | quote }}
      {{- end }}
      {{- if .Values.externalSecrets.bitwardensecretsmanager.identityURL }}
      identityURL: {{ .Values.externalSecrets.bitwardensecretsmanager.identityURL | quote }}
      {{- end }}
      bitwardenServerSDKURL: {{ .Values.externalSecrets.bitwardensecretsmanager.bitwardenServerSDKURL | quote }}
      {{- if .Values.externalSecrets.bitwardensecretsmanager.caBundle }}
      caBundle: {{ .Values.externalSecrets.bitwardensecretsmanager.caBundle | quote }}
      {{- end }}
{{- end }}
